services:
  db:
    image: postgres
    container_name: budget-app-postgress
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=budget
      - POSTGRES_USER=budget
      - POSTGRES_PASSWORD=password
    volumes:
      - budget-app-db:/var/lib/postgresql/data
    restart: always

  budget-app:
    image: budget-app
    build: .
    container_name: budget-app-container
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/budget
      - DB_USER=budget
      - DB_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/budget
      - SPRING_DATASOURCE_USERNAME=budget
      - SPRING_DATASOURCE_PASSWORD=password
      - DB_DRIVER=org.postgresql.Driver
    depends_on:
      - db
    restart: always

volumes:
  budget-app-db: